name: pixel_todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  get_it: ^8.0.2
  hive_flutter: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13 

flutter:
  uses-material-design: true
  assets:
    - assets/images/stub_hero.png
    - assets/images/delete_task.png

    - assets/images/low_priority.png
    - assets/images/medium_priority.png
    - assets/images/top_priority.png

    - assets/images/easy_difficulty.png
    - assets/images/medium_difficulty.png
    - assets/images/hard_difficulty.png
    - assets/images/insane_difficulty.png

    - assets/images/pergament.png
    - assets/images/feather.png
    - assets/images/wooden_background_desk.png
  
  fonts:
    - family: TeletactileRus
      fonts:
      - asset: assets\fonts\TeletactileRus.ttf
