// d:\develop\flutter_projects\pixel_todo\lib\features\taskDetail\view.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'task_details_screen.dart';
